"""Player matching utilities for ESPN ID mapping."""

import csv
import json
from pathlib import Path

from rapidfuzz import fuzz, process

import config

# Cyrillic to ASCII character mappings
CYRILLIC_TO_ASCII = {
    '\u0435': 'e',  # Cyrillic е -> e
    '\u0430': 'a',  # Cyrillic а -> a
    '\u043e': 'o',  # Cyrillic о -> o
    '\u0440': 'p',  # Cyrillic р -> p (looks like p)
    '\u0441': 'c',  # Cyrillic с -> c
    '\u0443': 'y',  # Cyrillic у -> y
    '\u0445': 'x',  # Cyrillic х -> x
}


def normalize_name(name: str) -> str:
    """Normalize a name for comparison.

    Args:
        name: Player name to normalize

    Returns:
        Lowercase name with Cyrillic chars replaced and whitespace stripped
    """
    # Lowercase
    result = name.lower()

    # Replace Cyrillic lookalikes with ASCII
    for cyrillic, ascii_char in CYRILLIC_TO_ASCII.items():
        result = result.replace(cyrillic, ascii_char)

    # Strip whitespace
    return result.strip()


def find_best_match(
    golfer_name: str,
    espn_players: list[dict],
    threshold: int = 70
) -> tuple[str | None, str | None, int]:
    """Find the best matching ESPN player for a golfer name.

    Args:
        golfer_name: Name to match
        espn_players: List of ESPN player dicts with 'name' and 'athlete_id'
        threshold: Minimum score to consider a match (0-100)

    Returns:
        Tuple of (espn_name, espn_id, confidence_score)
        Returns (None, None, score) if no match above threshold
    """
    if not espn_players:
        return (None, None, 0)

    normalized_input = normalize_name(golfer_name)

    # Build lookup dict: normalized_name -> player
    player_lookup = {}
    choices = []
    for player in espn_players:
        norm = normalize_name(player["name"])
        player_lookup[norm] = player
        choices.append(norm)

    # Use token_sort_ratio for word order flexibility
    result = process.extractOne(
        normalized_input,
        choices,
        scorer=fuzz.token_sort_ratio
    )

    if result is None:
        return (None, None, 0)

    matched_norm, score, _ = result

    if score < threshold:
        return (None, None, score)

    player = player_lookup[matched_norm]
    return (player["name"], player["athlete_id"], score)


def get_status(confidence: int) -> str:
    """Determine match status from confidence score."""
    if confidence >= 95:
        return "MATCH"
    elif confidence >= 70:
        return "REVIEW"
    else:
        return "NO_MATCH"


def match_golfers(
    golfers: list[dict],
    espn_players: list[dict]
) -> list[dict]:
    """Match a list of golfers against ESPN players.

    Args:
        golfers: List of dicts with 'golfer_id' and 'name'
        espn_players: List of ESPN player dicts

    Returns:
        List of match result dicts
    """
    results = []

    for golfer in golfers:
        espn_name, espn_id, confidence = find_best_match(
            golfer["name"],
            espn_players
        )

        results.append({
            "golfer_id": golfer["golfer_id"],
            "current_name": golfer["name"],
            "espn_name": espn_name or "",
            "espn_id": espn_id or "",
            "confidence": confidence,
            "status": get_status(confidence),
        })

    return results


def read_golfers_csv(filepath: str) -> list[dict]:
    """Read golfers from a CSV file.

    Expected columns: golfer_id, name (additional columns ignored)

    Args:
        filepath: Path to CSV file

    Returns:
        List of golfer dicts with golfer_id (int) and name (str)
    """
    golfers = []
    with open(filepath, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            golfers.append({
                "golfer_id": int(row["golfer_id"]),
                "name": row["name"],
            })
    return golfers


def write_mapping_csv(results: list[dict], filepath: str) -> None:
    """Write matching results to a CSV file.

    Args:
        results: List of match result dicts
        filepath: Output path
    """
    fieldnames = ["golfer_id", "current_name", "espn_name", "espn_id", "confidence", "status"]

    with open(filepath, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)


def generate_sql_updates(results: list[dict]) -> str:
    """Generate SQL UPDATE statements from matching results.

    Args:
        results: List of match result dicts from match_golfers

    Returns:
        SQL script as string
    """
    lines = [
        "-- Generated by gscraper match-golfers",
        "-- Review before running in Neon console",
        "",
    ]

    for r in results:
        espn_id = r.get("espn_id", "")
        if not espn_id:
            continue  # Skip unmatched

        golfer_id = r["golfer_id"]
        current_name = r["current_name"]
        espn_name = r.get("espn_name", "")

        # Escape single quotes for SQL
        espn_name_escaped = espn_name.replace("'", "''")
        espn_id_escaped = espn_id.replace("'", "''")

        # Check if name needs updating
        if current_name != espn_name and espn_name:
            # Update both name and espn_id
            lines.append(f"-- {current_name}: name fix + ESPN ID")
            lines.append(
                f"UPDATE golfers SET name = '{espn_name_escaped}', "
                f"espn_id = '{espn_id_escaped}' WHERE golfer_id = {golfer_id};"
            )
        else:
            # Update espn_id only
            lines.append(f"-- {current_name}: ESPN ID only")
            lines.append(
                f"UPDATE golfers SET espn_id = '{espn_id_escaped}' "
                f"WHERE golfer_id = {golfer_id};"
            )
        lines.append("")

    return "\n".join(lines)


def load_players_from_tournament_results() -> list[dict]:
    """Load all unique players from tournament result files.

    Returns:
        List of player dicts with 'athlete_id' and 'name'
    """
    players = {}  # Use dict to dedupe by athlete_id

    results_dir = config.TOURNAMENT_RESULTS_DIR
    if not results_dir.exists():
        return []

    for json_file in results_dir.glob("*.json"):
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            for result in data.get("results", []):
                athlete_id = result.get("athlete_id")
                name = result.get("name")
                if athlete_id and name and athlete_id not in players:
                    players[athlete_id] = {
                        "athlete_id": athlete_id,
                        "name": name,
                    }
        except (json.JSONDecodeError, KeyError):
            continue

    return list(players.values())


def load_all_espn_players() -> list[dict]:
    """Load players from all available local sources.

    Combines:
    - fedex_standings.json (top 50)
    - tournament_results/*.json (everyone who scored points)

    Returns:
        Deduplicated list of player dicts with 'athlete_id' and 'name'
    """
    from scrapers.fedex_standings import load_player_roster

    players = {}  # Dedupe by athlete_id

    # Load from fedex standings
    try:
        for player in load_player_roster():
            aid = player.get("athlete_id")
            if aid:
                players[aid] = {"athlete_id": aid, "name": player.get("name", "")}
    except Exception:
        pass

    # Load from tournament results
    for player in load_players_from_tournament_results():
        aid = player.get("athlete_id")
        if aid and aid not in players:
            players[aid] = player

    return list(players.values())


def search_golfer_espn(golfer_name: str, client=None) -> tuple[str | None, str | None]:
    """Search ESPN for a golfer by name.

    Uses ESPN's search API to find any golfer, not just those in current tournaments.

    Args:
        golfer_name: Name to search for
        client: Optional ESPNClient

    Returns:
        Tuple of (espn_name, espn_id) or (None, None) if not found
    """
    if client is None:
        from espn_client import ESPNClient
        client = ESPNClient()

    try:
        data = client.search_player(golfer_name)
        if not data:
            return (None, None)

        results = data.get("results", [])

        # Look for golf players in search results
        for result in results:
            # Check if this is a player result
            if result.get("type") != "player":
                continue

            contents = result.get("contents", [])
            for player in contents:
                # Extract the uid field: "s:1100~a:462" -> extract athlete_id "462"
                uid = player.get("uid", "")

                # uid format: "s:{sport_id}~a:{athlete_id}"
                # Golf sport ID is 1100
                if "~a:" not in uid:
                    continue

                # Check if this is a golf player (sport ID 1100)
                if not uid.startswith("s:1100~"):
                    continue

                # Extract athlete_id from uid
                athlete_id = uid.split("~a:")[-1]
                display_name = player.get("displayName", "")

                if athlete_id and display_name:
                    return (display_name, athlete_id)

        return (None, None)

    except Exception:
        return (None, None)


def lookup_golfer_espn(golfer_name: str, client=None) -> tuple[str | None, str | None, int]:
    """Look up a golfer using ESPN's search API, with tournament field as backup.

    Prioritizes the search API for accurate results, falls back to tournament
    field fuzzy matching if search fails.

    Args:
        golfer_name: Name to search for
        client: Optional ESPNClient instance

    Returns:
        Tuple of (espn_name, espn_id, confidence) or (None, None, 0) if not found
    """
    if client is None:
        from espn_client import ESPNClient
        client = ESPNClient()

    # First, try search API (most accurate)
    try:
        espn_name, espn_id = search_golfer_espn(golfer_name, client)
        if espn_id:
            # Search API returns exact match, so use high confidence
            return (espn_name, espn_id, 100)
    except Exception:
        pass

    # Fallback: try current tournament field with fuzzy matching
    try:
        scoreboard = client.get_scoreboard()
        events = scoreboard.get("events", [])

        if events:
            # Build field from current tournament
            field = []
            current_event = events[0]
            competitions = current_event.get("competitions", [])
            if competitions:
                competitors = competitions[0].get("competitors", [])
                for competitor in competitors:
                    athlete = competitor.get("athlete", {})
                    field.append({
                        "athlete_id": str(competitor.get("id", "")),
                        "name": athlete.get("displayName", ""),
                    })

            # Use existing fuzzy match
            name, espn_id, confidence = find_best_match(golfer_name, field)
            if espn_id:
                return (name, espn_id, confidence)

    except Exception:
        pass

    return (None, None, 0)


def match_golfers_enhanced(
    golfers: list[dict],
    espn_players: list[dict] | None = None,
    lookup_unmatched: bool = True,
    client=None,
) -> list[dict]:
    """Match golfers with local data first, then ESPN API for unmatched.

    Args:
        golfers: List of dicts with 'golfer_id' and 'name'
        espn_players: Optional pre-loaded ESPN players (uses load_all_espn_players if None)
        lookup_unmatched: Whether to query ESPN API for NO_MATCH results
        client: Optional ESPNClient for API lookups

    Returns:
        List of match result dicts
    """
    # Load comprehensive local player list if not provided
    if espn_players is None:
        espn_players = load_all_espn_players()

    # First pass: match against local data
    results = match_golfers(golfers, espn_players)

    if not lookup_unmatched:
        return results

    # Second pass: ESPN API lookup for unmatched
    unmatched_indices = [
        i for i, r in enumerate(results) if r["status"] == "NO_MATCH"
    ]

    if not unmatched_indices:
        return results

    # Initialize client once for all lookups
    if client is None:
        from espn_client import ESPNClient
        client = ESPNClient()

    for idx in unmatched_indices:
        golfer_name = results[idx]["current_name"]
        espn_name, espn_id, confidence = lookup_golfer_espn(golfer_name, client)

        if espn_id:
            results[idx]["espn_name"] = espn_name
            results[idx]["espn_id"] = espn_id
            results[idx]["confidence"] = confidence
            results[idx]["status"] = get_status(confidence)

    return results
